PKG_NAME = whitefield
PKG_VERSION = 123456
PKG_LICENSE = gpl2
PKG_DIR=$(CURDIR)
PKG_BUILDDIR=$(PKGDIRBASE)/$(PKG_NAME)
PKG_SRCDIR=$(PKG_BUILDDIR)/src

MODULE_MAKEFILE := $(PKG_DIR)/Makefile.module

.PHONY: all clean distclean

all:

clean::
	rm -rf $(PKG_BUILDDIR)/

distclean::
	rm -rf $(PKG_BUILDDIR)/
